# _config.yml

title: "Veridian: El Lenguaje de Programación"
description: "Un lenguaje que fusiona la facilidad de uso, el rendimiento y la seguridad."

# Elige un tema. 'minima' es el por defecto, pero 'just-the-docs' es excelente para documentación.
# Para usarlo, sigue las instrucciones de ese tema. Empecemos con el básico.
theme: minima 
