# _config.yml

title: "Veridian Lang"
description: "Un lenguaje de programación que fusiona la facilidad de uso, el rendimiento y la seguridad."

# Para el correcto funcionamiento en GitHub Pages.
# 'just-the-docs' es excelente para documentación.
theme: minima
